import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileDown, CheckCircle2, Download } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { planService, topicService, videoService, progressService } from '../lib/api';

interface Plan {
  id: string;
  title: string;
  created_at: string;
}

export default function ExportPDF() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [selectedPlanId, setSelectedPlanId] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    loadPlans();
  }, []);

  const loadPlans = async () => {
    try {
      const loadedPlans = await planService.getPlans();
      setPlans(loadedPlans);
      if (loadedPlans.length > 0) {
        setSelectedPlanId(loadedPlans[0].id);
      }
    } catch (error) {
      console.error('Error loading plans:', error);
    }
  };

  const handleExportPDF = async () => {
    if (!selectedPlanId) return;

    setLoading(true);
    setSuccess(false);

    try {
      const plan = await planService.getPlan(selectedPlanId);
      const topics = await topicService.getTopicsByPlan(selectedPlanId);
      const allProgress = await progressService.getAllProgress();

      const topicsWithData = await Promise.all(
        topics.map(async (topic) => {
          const videos = await videoService.getVideosByTopic(topic.id);
          const progress = allProgress.find((p) => p.topic_id === topic.id);
          return {
            ...topic,
            videos,
            progress: progress?.progress_percentage || 0,
          };
        })
      );

      const pdfContent = `
<!DOCTYPE html>
<html>
<head>
  <title>${plan.title} - Study Plan</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    h1 {
      color: #2563EB;
      border-bottom: 3px solid #2563EB;
      padding-bottom: 10px;
    }
    h2 {
      color: #1e40af;
      margin-top: 30px;
    }
    .topic {
      background: #f8fafc;
      padding: 20px;
      margin: 20px 0;
      border-radius: 8px;
      border-left: 4px solid #2563EB;
    }
    .difficulty {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: bold;
      margin-left: 10px;
    }
    .beginner { background: #d1fae5; color: #065f46; }
    .intermediate { background: #fef3c7; color: #92400e; }
    .advanced { background: #fee2e2; color: #991b1b; }
    .progress-bar {
      width: 100%;
      height: 20px;
      background: #e5e7eb;
      border-radius: 10px;
      overflow: hidden;
      margin: 10px 0;
    }
    .progress-fill {
      height: 100%;
      background: linear-gradient(to right, #2563EB, #0EA5E9);
    }
    .video-list {
      margin-top: 15px;
    }
    .video-item {
      padding: 8px;
      background: white;
      margin: 5px 0;
      border-radius: 4px;
    }
    .meta {
      color: #6b7280;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <h1>${plan.title}</h1>
  <p class="meta">Generated on ${new Date().toLocaleDateString()}</p>

  ${topicsWithData
    .map(
      (topic, index) => `
    <div class="topic">
      <h2>${index + 1}. ${topic.title}
        <span class="difficulty ${topic.difficulty.toLowerCase()}">${topic.difficulty}</span>
      </h2>
      <p>${topic.description || 'No description available'}</p>
      <p class="meta">Estimated time: ${topic.estimated_minutes} minutes</p>

      <div>
        <strong>Progress: ${topic.progress}%</strong>
        <div class="progress-bar">
          <div class="progress-fill" style="width: ${topic.progress}%"></div>
        </div>
      </div>

      ${
        topic.videos.length > 0
          ? `
        <div class="video-list">
          <strong>Recommended Videos:</strong>
          ${topic.videos
            .map(
              (video: any) => `
            <div class="video-item">
              <strong>${video.title}</strong><br/>
              <span class="meta">${video.channel} - ${video.url}</span>
            </div>
          `
            )
            .join('')}
        </div>
      `
          : ''
      }
    </div>
  `
    )
    .join('')}

  <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280;">
    <p>Generated by SyllabusPath AI</p>
  </div>
</body>
</html>
      `.trim();

      const blob = new Blob([pdfContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${plan.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_study_plan.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      setSuccess(true);
      setTimeout(() => setSuccess(false), 5000);
    } catch (error) {
      console.error('Error exporting PDF:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <Navbar />

      <main className="flex-1 py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-8"
          >
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Export Study Plan</h1>
            <p className="text-gray-600">Download your study plan as a PDF document</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white rounded-xl shadow-md p-8"
          >
            {plans.length === 0 ? (
              <div className="text-center py-12">
                <FileDown className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-gray-900 mb-2">No Plans Found</h3>
                <p className="text-gray-600">Create a study plan first to export it as PDF</p>
              </div>
            ) : (
              <div className="space-y-6">
                {success && (
                  <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="bg-green-50 border border-green-200 text-green-700 p-4 rounded-lg flex items-center space-x-3"
                  >
                    <CheckCircle2 className="w-5 h-5 flex-shrink-0" />
                    <span className="font-medium">
                      Study plan exported successfully! Check your downloads folder.
                    </span>
                  </motion.div>
                )}

                <div>
                  <label htmlFor="plan" className="block text-sm font-medium text-gray-700 mb-2">
                    Select Study Plan
                  </label>
                  <select
                    id="plan"
                    value={selectedPlanId}
                    onChange={(e) => setSelectedPlanId(e.target.value)}
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    {plans.map((plan) => (
                      <option key={plan.id} value={plan.id}>
                        {plan.title} - Created {new Date(plan.created_at).toLocaleDateString()}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <h3 className="font-semibold text-blue-900 mb-2 flex items-center">
                    <Download className="w-5 h-5 mr-2" />
                    Export Information
                  </h3>
                  <ul className="text-sm text-blue-800 space-y-1 list-disc list-inside">
                    <li>The plan will be exported as an HTML document</li>
                    <li>Includes all topics, videos, and progress data</li>
                    <li>You can print it to PDF from your browser</li>
                    <li>The file will be saved to your downloads folder</li>
                  </ul>
                </div>

                <button
                  onClick={handleExportPDF}
                  disabled={loading || !selectedPlanId}
                  className="w-full py-4 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-lg hover:from-blue-700 hover:to-cyan-700 transition-all font-semibold shadow-md hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
                >
                  {loading ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      <span>Exporting...</span>
                    </>
                  ) : (
                    <>
                      <FileDown className="w-5 h-5" />
                      <span>Export as PDF</span>
                    </>
                  )}
                </button>
              </div>
            )}
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-6 bg-white rounded-xl shadow-md p-6"
          >
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Tips for Best Results</h2>
            <div className="space-y-2 text-gray-600">
              <p className="flex items-start">
                <span className="font-semibold text-blue-600 mr-2">1.</span>
                After downloading, open the HTML file in your browser
              </p>
              <p className="flex items-start">
                <span className="font-semibold text-blue-600 mr-2">2.</span>
                Use your browser's print function to save as PDF
              </p>
              <p className="flex items-start">
                <span className="font-semibold text-blue-600 mr-2">3.</span>
                Select "Save as PDF" as the destination
              </p>
              <p className="flex items-start">
                <span className="font-semibold text-blue-600 mr-2">4.</span>
                Adjust margins and layout as needed
              </p>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
